name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # Run tests.
  test:
    if: ${{ !contains(github.event.head_commit.message, 'docs') }}
    strategy:
      matrix:
        go-version: [1.16.x]
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test ./...
